drm/rockchip: include drm_plane.h for rockchip_drm_vop.h
Fix the follow compile error:
In file included from drivers/gpu/drm/rockchip/rockchip_vop2_reg.c:10:
drivers/gpu/drm/rockchip/rockchip_drm_vop.h:196:22: error: field has
incomplete type 'enum drm_plane_type'
        enum drm_plane_type type;
                            ^
drivers/gpu/drm/rockchip/rockchip_drm_vop.h:196:7: note: forward
declaration of 'enum drm_plane_type'
        enum drm_plane_type type;

This is due to the remove of drmP.h:
commit 4e98f871bcff ("drm: delete drmP.h + drm_os_linux.h")

Signed-off-by: Andy Yan <andy.yan@rock-chips.com>
Change-Id: Ic7d1d58d5d4c9c032067c7686c76cef41a92a5d2